// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlasticPackagingPortal.Web.Data;

#nullable disable

namespace PlasticPackagingPortal.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Colours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentRecyclingDisruptors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Depth")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DepthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Flexibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime?>("HeightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturedCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PartOfMultipack")
                        .HasColumnType("bit");

                    b.Property<string>("Recyclability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RecyclabilityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecyclabilitySource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContentEvidenceReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContentEvidenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReuseSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SystemUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Volume")
                        .HasColumnType("float");

                    b.Property<DateTime?>("VolumeDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime?>("WeightDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("WeightTolerance")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.Property<DateTime?>("WidthDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.StagingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Colours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComponentRecyclingDisruptors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscontinuedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flexibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeightDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturedCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartOfMultipack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recyclability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecyclabilityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecyclabilitySource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContentEvidenceReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecycledContentEvidenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReuseSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SystemUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightTolerance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WidthDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StagingItems");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.StagingTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SystemUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("StagingTags");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SystemCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SystemUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.StagingTag", b =>
                {
                    b.HasOne("PlasticPackagingPortal.Web.Models.Data.StagingItem", "Item")
                        .WithMany("Tags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.Tag", b =>
                {
                    b.HasOne("PlasticPackagingPortal.Web.Models.Data.Item", "Item")
                        .WithMany("Tags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.Item", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PlasticPackagingPortal.Web.Models.Data.StagingItem", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
